name: CI/CD Pipeline

on:
  push:
    branches:
      - dev 
  pull_request:
    branches:
      - dev  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build  

  merge:
    runs-on: ubuntu-latest
    needs: build  
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge dev into main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          git checkout main
          git merge origin/dev -X theirs -m "Automated merge from dev to main" --allow-unrelated-histories
          git push origin main

  deploy:
    runs-on: ubuntu-latest
    needs: merge  
    steps:
      - name: Trigger Vercel Deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_UNbOH0MsWLcnANTD7DeqJ17JYpas/Rk0IUkELGN" \
          -H "Authorization: Bearer $VERCEL_TOKEN"
